

create table if not exists TEAMS (
	ID integer auto_increment primary key,
	NAME varchar(255) not null
);


create table if not exists MATCHES (
	ID integer auto_increment primary key,
	OPPONENT_ID int not null,
	MATCH_DATE DATE,
	OUR_SCORE TINYINT,
	OPPONENT_SCORE TINYINT,
	INDEX ix_opponent (OPPONENT_ID),
    FOREIGN KEY (OPPONENT_ID)
        REFERENCES TEAMS(ID)
	
);


delete from matches;

delete from teams;

INSERT INTO TEAMS (NAME) VALUES ('G2');
SET @id = LAST_INSERT_ID();

INSERT INTO MATCHES(OPPONENT_ID, MATCH_DATE, OUR_SCORE, OPPONENT_SCORE) VALUES (@id, '2019-08-12', 5, 16);
INSERT INTO MATCHES(OPPONENT_ID, MATCH_DATE, OUR_SCORE, OPPONENT_SCORE) VALUES (@id, '2019-10-01', 16, 15);
INSERT INTO MATCHES(OPPONENT_ID, MATCH_DATE, OUR_SCORE, OPPONENT_SCORE) VALUES (@id, '2019-10-09', 15, 15);

INSERT INTO TEAMS (NAME) VALUES ('fnatic');
SET @id = LAST_INSERT_ID();

INSERT INTO MATCHES(OPPONENT_ID, MATCH_DATE, OUR_SCORE, OPPONENT_SCORE) VALUES (@id, '2019-10-22', 12, 16);
INSERT INTO MATCHES(OPPONENT_ID, MATCH_DATE, OUR_SCORE, OPPONENT_SCORE) VALUES (@id, '2019-10-18', 10, 16);
INSERT INTO MATCHES(OPPONENT_ID, MATCH_DATE, OUR_SCORE, OPPONENT_SCORE) VALUES (@id, '2019-10-13', 15, 15);

INSERT INTO TEAMS (NAME) VALUES ('Astralis');
SET @id = LAST_INSERT_ID();

INSERT INTO MATCHES(OPPONENT_ID, MATCH_DATE, OUR_SCORE, OPPONENT_SCORE) VALUES (@id, '2019-09-12', 1, 16);
INSERT INTO MATCHES(OPPONENT_ID, MATCH_DATE, OUR_SCORE, OPPONENT_SCORE) VALUES (@id, '2019-10-31', 2, 16);
INSERT INTO MATCHES(OPPONENT_ID, MATCH_DATE, OUR_SCORE, OPPONENT_SCORE) VALUES (@id, '2019-11-1', 13, 16);

INSERT INTO TEAMS (NAME) VALUES ('Evil Geniuses');
SET @id = LAST_INSERT_ID();

INSERT INTO MATCHES(OPPONENT_ID, MATCH_DATE, OUR_SCORE, OPPONENT_SCORE) VALUES (@id, '2019-10-14', 16, 7);
INSERT INTO MATCHES(OPPONENT_ID, MATCH_DATE, OUR_SCORE, OPPONENT_SCORE) VALUES (@id, '2019-10-13', 16, 8);
INSERT INTO MATCHES(OPPONENT_ID, MATCH_DATE, OUR_SCORE, OPPONENT_SCORE) VALUES (@id, '2019-10-12', 16, 13);


SELECT NAME, OUR_SCORE, OPPONENT_SCORE, MATCH_DATE FROM
MATCHES m INNER JOIN TEAMS t ON m.OPPONENT_ID = t.ID;